# Generated by Django 6.0 on 2025-12-25 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='nick',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='question',
            name='title',
            field=models.CharField(default='сСтары й вопрос', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='questionlike',
            name='is_like',
            field=models.BooleanField(default=True),
        ),
    ]
